Repository AY2223S2-CS2103T-T17-1/tp, pull requests merged in 2023-03, with the labels that each got.

#11 Update AboutUs for William, close #5
  .gitignore
  docs/AboutUs.md
  docs/images/willcwx.png
  docs/team/willcwx.md
Labels: help wanted

#16 Update DG
  docs/DeveloperGuide.md
Labels: documentation, help wanted

#14 Update README.md, close #4
  .gitignore
  README.md
  copyright.txt
  docs/Gemfile.lock
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/images/Ui.png
  docs/index.md
Labels: help wanted

#25 Update UG, close #12
  docs/UserGuide.md
Labels: documentation, priority.High

#38 Add sorting
  src/main/java/teambuilder/commons/core/Messages.java
  src/main/java/teambuilder/logic/LogicManager.java
  src/main/java/teambuilder/logic/commands/DeleteCommand.java
  src/main/java/teambuilder/logic/commands/EditCommand.java
  src/main/java/teambuilder/logic/commands/FindCommand.java
  src/main/java/teambuilder/logic/commands/SortCommand.java
  src/main/java/teambuilder/logic/commands/enums/SortBy.java
  src/main/java/teambuilder/logic/parser/SortCommandParser.java
  src/main/java/teambuilder/logic/parser/TeamBuilderParser.java
  src/main/java/teambuilder/model/Model.java
  src/main/java/teambuilder/model/ModelManager.java
  src/main/java/teambuilder/model/person/Person.java
  src/test/java/teambuilder/logic/commands/AddCommandTest.java
  src/test/java/teambuilder/logic/commands/CommandTestUtil.java
  src/test/java/teambuilder/logic/commands/DeleteCommandTest.java
  src/test/java/teambuilder/logic/commands/EditCommandTest.java
  src/test/java/teambuilder/logic/commands/FindCommandTest.java
  src/test/java/teambuilder/logic/commands/SortCommandTest.java
  src/test/java/teambuilder/logic/commands/UndoCommandTest.java
  src/test/java/teambuilder/logic/parser/TeamBuilderParserTest.java
  src/test/java/teambuilder/model/ModelManagerTest.java
  src/test/java/teambuilder/testutil/TestUtil.java
Labels: priority.High

#42 Team Tags Feature
  src/main/java/teambuilder/logic/commands/EditCommand.java
  src/main/java/teambuilder/logic/parser/AddCommandParser.java
  src/main/java/teambuilder/logic/parser/CliSyntax.java
  src/main/java/teambuilder/model/person/Person.java
  src/main/java/teambuilder/model/tag/Tag.java
  src/main/java/teambuilder/model/util/SampleDataUtil.java
  src/main/java/teambuilder/storage/JsonAdaptedPerson.java
  src/main/java/teambuilder/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/teambuilder/storage/JsonAdaptedPersonTest.java
  src/test/java/teambuilder/testutil/EditPersonDescriptorBuilder.java
  src/test/java/teambuilder/testutil/PersonBuilder.java
Labels: type.Story, priority.High

#43 Added tests for team tags
  src/test/java/teambuilder/logic/parser/ParserUtilTest.java
Labels: type.Story, priority.High

#50 Update Jerry's PPP
  docs/AboutUs.md
  docs/team/chen-jerry-junior.md
Labels: documentation

#49 Modify the edit command and parser for teamTags
  src/main/java/teambuilder/logic/commands/EditCommand.java
  src/main/java/teambuilder/logic/parser/EditCommandParser.java
  src/test/java/teambuilder/logic/LogicManagerTest.java
  src/test/java/teambuilder/logic/commands/CommandTestUtil.java
  src/test/java/teambuilder/logic/parser/TeamBuilderParserTest.java
  src/test/java/teambuilder/testutil/EditPersonDescriptorBuilder.java
  src/test/java/teambuilder/testutil/PersonUtil.java
Labels: priority.Medium

#53 Update Add and Edit command parser for TeamTags
  src/main/java/teambuilder/logic/commands/EditCommand.java
  src/main/java/teambuilder/logic/parser/AddCommandParser.java
  src/main/java/teambuilder/logic/parser/EditCommandParser.java
  src/test/java/teambuilder/testutil/PersonUtil.java
Labels: type.Bug

#57 Update Wei Xun PPP
  docs/AboutUs.md
  docs/team/swx0.md
Labels: documentation

#58 Move points to New Feature section
  docs/team/swx0.md
Labels: documentation

#62 Enable assertions in build.gradle
  build.gradle
Labels: priority.High, type.Test

#63 Make phone optional
  src/main/java/teambuilder/logic/parser/AddCommandParser.java
  src/main/java/teambuilder/logic/parser/ParserUtil.java
  src/main/java/teambuilder/model/person/Email.java
  src/main/java/teambuilder/model/person/Person.java
  src/main/java/teambuilder/model/person/Phone.java
  src/main/java/teambuilder/model/util/SampleDataUtil.java
  src/main/java/teambuilder/storage/JsonAdaptedPerson.java
  src/main/java/teambuilder/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/teambuilder/logic/parser/AddCommandParserTest.java
  src/test/java/teambuilder/logic/parser/ParserUtilTest.java
  src/test/java/teambuilder/model/person/EmailTest.java
  src/test/java/teambuilder/model/person/PhoneTest.java
  src/test/java/teambuilder/model/util/SampleDataUtilTest.java
  src/test/java/teambuilder/testutil/EditPersonDescriptorBuilder.java
  src/test/java/teambuilder/testutil/PersonBuilder.java
Labels: type.Epic, type.Enhancement, priority.High

#69 Add sort command implementation detail to DG
  docs/DeveloperGuide.md
Labels: documentation

#72 Add get team implementation in DeveloperGuide
  docs/DeveloperGuide.md
Labels: documentation

#80 Teamlist and associated commands
  src/main/java/teambuilder/commons/core/Messages.java
  src/main/java/teambuilder/logic/commands/AddCommand.java
  src/main/java/teambuilder/logic/commands/CreateCommand.java
  src/main/java/teambuilder/logic/commands/DeleteCommand.java
  src/main/java/teambuilder/logic/commands/EditCommand.java
  src/main/java/teambuilder/logic/commands/RemoveCommand.java
  src/main/java/teambuilder/logic/parser/RemoveCommandParser.java
  src/main/java/teambuilder/logic/parser/TeamBuilderParser.java
  src/main/java/teambuilder/model/Model.java
  src/main/java/teambuilder/model/ModelManager.java
  src/main/java/teambuilder/model/ReadOnlyTeamBuilder.java
  src/main/java/teambuilder/model/TeamBuilder.java
  src/main/java/teambuilder/model/person/Person.java
  src/main/java/teambuilder/model/tag/Tag.java
  src/main/java/teambuilder/model/team/Team.java
  src/main/java/teambuilder/model/team/UniqueTeamList.java
  src/main/java/teambuilder/model/team/exceptions/DuplicateTeamException.java
  src/main/java/teambuilder/model/team/exceptions/TeamNotFoundException.java
  src/main/java/teambuilder/model/util/SampleDataUtil.java
  src/test/java/teambuilder/logic/commands/AddCommandTest.java
  src/test/java/teambuilder/logic/commands/RedoCommandIntegrationTest.java
  src/test/java/teambuilder/logic/commands/UndoCommandTest.java
  src/test/java/teambuilder/model/TeamBuilderTest.java
  src/test/java/teambuilder/model/person/UniqueTeamListTest.java
  src/test/java/teambuilder/testutil/TypicalTeams.java
Labels: priority.High

#89 Update Find Command
  src/main/java/teambuilder/logic/commands/FindCommand.java
  src/main/java/teambuilder/logic/parser/FindCommandParser.java
  src/main/java/teambuilder/model/person/NameContainsKeywordsPredicate.java
  src/main/java/teambuilder/model/person/PersonContainsKeywordsPredicate.java
  src/test/java/teambuilder/logic/commands/CommandTestUtil.java
  src/test/java/teambuilder/logic/commands/FindCommandTest.java
  src/test/java/teambuilder/logic/parser/FindCommandParserTest.java
  src/test/java/teambuilder/logic/parser/TeamBuilderParserTest.java
  src/test/java/teambuilder/model/ModelManagerTest.java
  src/test/java/teambuilder/model/person/PersonContainsKeywordsPredicateTest.java
Labels: type.Story, type.Enhancement, priority.High

#93 Update UserGuide based on CS2101 standard
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/JohnContactCardBack.jpg
  docs/images/JohnContactCardFront.png
  docs/images/helpMessage.png
  docs/index.md
Labels: documentation, priority.Medium

#92 Add Show person in Team feature
  src/main/java/teambuilder/logic/commands/ShowCommand.java
  src/main/java/teambuilder/logic/parser/ShowCommandParser.java
  src/main/java/teambuilder/logic/parser/TeamBuilderParser.java
  src/main/java/teambuilder/model/person/TeamContainsKeywordsPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/teambuilder/logic/commands/ShowCommandTest.java
  src/test/java/teambuilder/logic/parser/ShowCommandParserTest.java
  src/test/java/teambuilder/logic/parser/TeamBuilderParserTest.java
  src/test/java/teambuilder/model/person/TeamContainsKeywordsPredicateTest.java
  src/test/java/teambuilder/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#94 Modify GUI to show the Team features
  src/main/java/teambuilder/model/team/Team.java
  src/main/java/teambuilder/ui/MainWindow.java
  src/main/java/teambuilder/ui/PersonCard.java
  src/main/java/teambuilder/ui/TeamCard.java
  src/main/java/teambuilder/ui/TeamListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TeamListCard.fxml
  src/main/resources/view/TeamListPanel.fxml
Labels: priority.High, type.GUI

#98 Update UG and DG for v1.3
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#97 Update RemoveCommand to remove TeamTags as well
  src/main/java/teambuilder/logic/commands/RemoveCommand.java
  src/test/java/teambuilder/logic/commands/UndoCommandIntegrationTest.java
Labels: priority.High

#99 Fix Json save and read behaviour
  src/main/java/teambuilder/storage/JsonAdaptedTeam.java
  src/main/java/teambuilder/storage/JsonSerializableTeamBuilder.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/teambuilder/storage/JsonSerializableTeamBuilderTest.java
  src/test/java/teambuilder/testutil/TypicalPersons.java
  src/test/java/teambuilder/testutil/TypicalTeams.java
Labels: type.Story, type.Enhancement, priority.Medium

#107 Add tests for Team
  src/main/java/teambuilder/model/util/SampleDataUtil.java
  src/test/java/teambuilder/model/team/TeamTest.java
  src/test/java/teambuilder/model/util/SampleDataUtilTest.java
  src/test/java/teambuilder/testutil/TeamBuilder.java
Labels: type.Test

#108 Fix broken links in UG
  docs/UserGuide.md
  docs/images/AddResult.png
  docs/images/JohnFullContact.png
  docs/images/JohnIndex.png
  docs/images/LabelledAppWindow.png
Labels: type.Bug, documentation
