Repository AY2223S2-CS2103T-T17-1/tp, pull requests merged in 2023-04, with the labels that each got.

#146 Add note for add command
  docs/UserGuide.md
Labels: type.Bug, documentation

#145 Remove 'listing all tags' subtitle from UG
  docs/UserGuide.md
Labels: type.Bug, documentation

#148 Update sort description and subheaders
  docs/UserGuide.md
  docs/images/findAlexDavid.png
  docs/images/sortDesc.png
Labels: type.Bug, documentation, priority.High

#152 Update DG for Team, TeamList classes, sort and create command
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/UpdateModelClassDiagram.png
  docs/images/sortcommand-activity.png
  docs/images/sortcommandparser.png
Labels: documentation, priority.High

#154 Fix Ui TeamList Clipping issue
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, priority.High, type.GUI

#155 Fix error message to consist with UG format
  src/main/java/teambuilder/logic/commands/AddCommand.java
  src/main/java/teambuilder/logic/commands/EditCommand.java
  src/main/java/teambuilder/logic/commands/RemoveCommand.java
  src/main/java/teambuilder/logic/commands/ShowCommand.java
  src/main/java/teambuilder/logic/commands/SortCommand.java
  src/main/java/teambuilder/ui/TeamCard.java
  src/main/java/teambuilder/ui/TeamListPanel.java
Labels: type.Bug, priority.High

#156 Add Show Team feature to PPP
  docs/team/chen-jerry-junior.md
Labels: documentation

#157 Modify every "address book" into "TeamBuilder"
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/johndoe.md
  docs/team/swx0.md
  docs/tutorials/AddRemark.md
  docs/tutorials/TracingCode.md
  src/main/java/teambuilder/MainApp.java
  src/main/java/teambuilder/logic/Logic.java
  src/main/java/teambuilder/logic/commands/AddCommand.java
  src/main/java/teambuilder/logic/commands/ClearCommand.java
  src/main/java/teambuilder/logic/commands/DeleteCommand.java
  src/main/java/teambuilder/logic/commands/EditCommand.java
  src/main/java/teambuilder/logic/commands/ExitCommand.java
  src/main/java/teambuilder/logic/commands/FindCommand.java
  src/main/java/teambuilder/logic/commands/ListCommand.java
  src/main/java/teambuilder/logic/commands/RemoveCommand.java
  src/main/java/teambuilder/logic/commands/SortCommand.java
  src/main/java/teambuilder/logic/commands/exceptions/CommandException.java
  src/main/java/teambuilder/model/Model.java
  src/main/java/teambuilder/model/ModelManager.java
  src/main/java/teambuilder/model/ReadOnlyTeamBuilder.java
  src/main/java/teambuilder/model/TeamBuilder.java
  src/main/java/teambuilder/model/person/Address.java
  src/main/java/teambuilder/model/person/Email.java
  src/main/java/teambuilder/model/person/Name.java
  src/main/java/teambuilder/model/person/Phone.java
  src/main/java/teambuilder/model/tag/Tag.java
  src/main/java/teambuilder/model/team/Team.java
  src/main/java/teambuilder/storage/JsonSerializableTeamBuilder.java
  src/test/java/teambuilder/logic/commands/CommandTestUtil.java
  src/test/java/teambuilder/logic/commands/DeleteCommandTest.java
  src/test/java/teambuilder/logic/commands/EditCommandTest.java
Labels: documentation

#159 Add note for sort command
  docs/UserGuide.md
Labels: documentation, priority.Medium

#160 Update UG
  docs/UserGuide.md
Labels: documentation, priority.Medium

#161 Update ug description
  docs/UserGuide.md
Labels: documentation, priority.Medium

#162 Update target audience
  docs/UserGuide.md
Labels: documentation

#164 Fix activity diagram
  docs/DeveloperGuide.md
  docs/images/newsortcommandparser.png
  docs/images/sortcommandparser.png
Labels: documentation

#165 Update PPP
  docs/team/swx0.md
Labels: documentation

#166 Edit DG and PPP @ChickenChiang
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram2.png
  docs/team/chickenchiang.md
Labels: documentation, priority.High

#167 Add planned Enhancements for DG
  docs/DeveloperGuide.md
Labels: documentation

#168 Update manual testing in DG
  docs/DeveloperGuide.md
  docs/team/swx0.md
Labels: documentation

#171 Finalize PPP for Jiarui
  docs/team/chen-jerry-junior.md
Labels: documentation

#176 Update DG for Jiarui's part
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ActivityDiagram_ShowCommand.puml
  docs/diagrams/ActivityDiagram_ShowCommandParser.puml
  docs/diagrams/ActivityDiagram_TeamContainsKeywordsPredicate.puml
  docs/images/ActivityDiagram_ShowCommand.png
  docs/images/ActivityDiagram_ShowCommandParser.png
  docs/images/ActivityDiagram_TeamContainsKeywordsPredicate.png
  docs/team/chen-jerry-junior.md
  docs/team/chickenchiang.md
  docs/team/swx0.md
Labels: documentation
